version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./lawieserviceacc.json:/app/lawieserviceacc.json:ro  
    environment:
      - WORKERS=${WORKERS:-1}  d
    command: >
      sh -c "
        WORKERS=\${WORKERS:-1} && 
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers \$WORKERS
      "
