version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./lawieserviceacc.json:/app/lawieserviceacc.json:ro  
    environment:
      - WORKERS=${WORKERS:-1}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`demo.lawie.app`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    command: >
      sh -c "
        WORKERS=\${WORKERS:-1} && 
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers \$WORKERS
      "

  traefik:
    image: traefik:v2.9
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=emon@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
